#
# https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#common-application-properties
#
# ES: Fichero de configuración para trabajar en modo desarrollo. 
#     Si la aplicación se arranca como launch-dev se utilizará esta configuración de la aplicación
#     En esta configuración el servidor embebido estará en modo "gestionado", se registrará en BC y desde ahí se podrán cargar contenedores, gestionar procesos y tareas humanas
# EN: Configuration file for working in development mode.
#     If the application is started as launch-dev, this application configuration will be used
#     In this configuration the embedded server will be in "managed" mode, it will register in BC and from there containers can be loaded, processes and human tasks can be managed

# ES: configuración del servidor
# EN: server configuration
server.address=0.0.0.0
server.port=8090

cxf.path=/rest

# ES: GENERAL, trazado
# EN: GENERAL, tracing
logging.level.org.springframework.security=TRACE
logging.level.org.kie.server.services.rest.KieServerRestImpl=TRACE

# ES: configuración consola h2
# EN: h2 console configuration
spring.h2.console.settings.trace=true
spring.h2.console.settings.web-allow-others=true

# ES: propiedades del sistema para la configuración del servidor
#     utilizar el prefijo system.properties y a continuación nombre de la propiedad y valor, si en el starter no está ya la propiedad disponible
# EN: system properties for server configuration
#     use the system.properties prefix and then property name and value, if the property is not already available in the starter

# ES: kie server config
# EN: kie server config
kieserver.serverId=kieserverapp-dev
kieserver.serverName=kieserverapp Dev
##PUT YOUR IP ADDRESS HERE (Vethernet), IN ORDER YOUR KIE SERVER COULD BE LOCATED FROM A DOCKER CONTAINER, OR LOCALHOST IF YOUR BUSINESS CENTRAL IS RUNNING DIRECTLY IN YOUR HOST
##this is the ip that identifies your localhost inside docker
kieserver.location=http://172.23.96.1:8090/rest/server
kieserver.user=kieserver
kieserver.pwd=kieserver1!
#kieserver.user=controllerUser
#kieserver.pwd=controllerUser

# ES: BC config, configuración del controlador
# EN: BC config, controller configuration
# https://docs.redhat.com/en/documentation/red_hat_process_automation_manager/7.7/html/managing_and_monitoring_kie_server/kie-server-configure-server-managed-by-central-proc#kie-server-configure-server-managed-by-central-proc
# ES: controllerUser tiene que estar configurado en BC con el rol rest-all
# EN: controllerUser must be configured in BC with the rest-all role
kieserver.controllers=http://localhost:8080/business-central/rest/controller

# ES: el usuario controllerUser tiene que estar dado de alta en business central con el rol rest-all, porque debe permitir acceder a la api del controlador
# EN: the controllerUser user must be registered in business central with the rest-all role, because it must allow access to the controller api
system.properties.org.kie.server.controller.pwd=controllerUser
system.properties.org.kie.server.controller.user=controllerUser

# ES: otras propiedades para la ejecución
# EN: other properties for execution

# ES: Permite realizar peticiones al motor de procesos en nombre de un usuario distinto al que se está conectando. Trabajo en modo agente.
# EN: Allows making requests to the process engine on behalf of a different user than the one connecting. Working in agent mode.
system.properties.org.kie.server.bypass.auth.user=true

# ES: kie server capabilities
# EN: kie server capabilities
kieserver.drools.enabled=true
kieserver.dmn.enabled=true
kieserver.jbpm.enabled=true
kieserver.jbpmui.enabled=true
kieserver.casemgmt.enabled=true
#kieserver.prometheus.enabled=true

# ES: sigo probando lo de las tareas humanas
# EN: still testing human tasks
#system.properties.org.jbpm.ht.admin.user=medico
    
# ES: grupo encargado de gestionar las tareas humanas, Imprescindible para gestionar tareas humanas de este motor desde BC
# EN: group in charge of managing human tasks, Essential for managing human tasks of this engine from BC
system.properties.org.jbpm.ht.admin.group=admin
#system.properties.org.jbpm.task.cleanup.enabled=false

# ES: jbpm configuration
# EN: jbpm configuration
jbpm.executor.enabled=false
#jbpm.executor.retries=5
#jbpm.executor.interval=3
#jbpm.executor.threadPoolSize=1
#jbpm.executor.timeUnit=SECONDS

# ES: más info en https://www.baeldung.com/spring-boot-h2-database
# EN: more info at https://www.baeldung.com/spring-boot-h2-database
# ES: data source configuration
# EN: data source configuration
spring.datasource.username=sa
spring.datasource.password=sa
spring.datasource.url=jdbc:h2:./target/spring-boot-jbpm

# ES: si lo quisiéramos como fichero???
# EN: if we wanted it as a file???
#spring.datasource.url=jdbc:h2:file:./target/spring-boot-jbpm   
spring.datasource.driver-class-name=org.h2.Driver

# ES: para facilitar la monitorización de la base de datos
#     activa la url http://localhost:8090/h2-console que permitirá ver la base de datos
# EN: to facilitate database monitoring
#     activates the url http://localhost:8090/h2-console that will allow viewing the database
spring.h2.console.enabled=true

# ES: configuración de hibernate
# EN: hibernate configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.properties.hibernate.show_sql=false
spring.jpa.properties.hibernate.hbm2ddl.auto=update
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# ES: configuración del gestior de transacciones
# EN: transaction manager configuration
spring.jta.narayana.transaction-manager-id=1

# ES: banner
# EN: banner
spring.banner.location=classpath:banner.txt
