package us.dit.muit.ass.kieserverapp;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/**
 * ES: Clase principal de la aplicación Spring Boot que actúa como servidor Kie.
 * Esta aplicación arranca un servidor Kie básico que puede ser gestionado por
 * Business Central en modo desarrollo. No carga contenedores al inicio, estos
 * deben ser desplegados posteriormente desde Business Central.
 * 
 * La aplicación integra elementos transversales comunes a muchos procesos de
 * negocio y permite la ejecución de procesos BPM, gestión de casos y tareas
 * humanas utilizando el motor de reglas y procesos de Red Hat Process
 * Automation Manager.
 * 
 * EN: Main Spring Boot application class that acts as a Kie Server.
 * This application starts a basic Kie server that can be managed by
 * Business Central in development mode. It doesn't load containers at startup,
 * these must be deployed later from Business Central.
 * 
 * The application integrates cross-cutting elements common to many business
 * processes and allows execution of BPM processes, case management and human
 * tasks using the Red Hat Process Automation Manager rules and process engine.
 * 
 * @author Generated by Maven archetype
 * @see org.springframework.boot.autoconfigure.SpringBootApplication
 * @see us.dit.muit.ass.kieserverapp.conf.DefaultWebSecurityConfig
 */
@SpringBootApplication
public class Application {

    /**
     * ES: Método principal que arranca la aplicación Spring Boot.
     * Inicia el contexto de Spring y configura automáticamente el servidor Kie
     * junto con todos los componentes necesarios para la ejecución de procesos.
     * 
     * EN: Main method that starts the Spring Boot application.
     * Initializes the Spring context and automatically configures the Kie server
     * along with all necessary components for process execution.
     * 
     * @param args ES: Argumentos de línea de comandos pasados a la aplicación
     *             EN: Command line arguments passed to the application
     */
    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

}